version: "3"
services:
  api:
    image: my-node-blog-app
    build: .
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo_db
    env_file:
      - .env

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
